### ISSUE TITLE
SystemUI Crash - device can't boot and reboot after bootanimation

### ISSUE THREAD

**Issue by AIV-97** [Octavi-OS/platform_frameworks_base#28]
UID: 10074
Flags: 0x20c8be0d
Package: com.android.systemui v31 (12)
Foreground: No
Process-Runtime: 772
Build: google/coral/coral:12/SP1A.210812.016.A1/7796139:user/release-keys
Loading-Progress: 1.0

java.lang.RuntimeException: Unable to get provider com.google.android.systemui.keyguard.KeyguardSliceProviderGoogle: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.android.systemui.statusbar.NotificationMediaManager.addCallback(com.android.systemui.statusbar.NotificationMediaManager$MediaListener)' on a null object reference
	at android.app.ActivityThread.installProvider(ActivityThread.java:7430)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6942)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6713)
	at android.app.ActivityThread.access$1500(ActivityThread.java:248)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2054)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7842)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.android.systemui.statusbar.NotificationMediaManager.addCallback(com.android.systemui.statusbar.NotificationMediaManager$MediaListener)' on a null object reference
	at com.android.systemui.keyguard.KeyguardSliceProvider.onCreateSliceProvider(KeyguardSliceProvider.java:316)
	at com.google.android.systemui.keyguard.KeyguardSliceProviderGoogle.onCreateSliceProvider(KeyguardSliceProviderGoogle.java:83)
	at androidx.slice.SliceProvider.onCreate(SliceProvider.java:211)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2404)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2374)
	at androidx.slice.SliceProvider.attachInfo(SliceProvider.java:250)
	at androidx.slice.compat.SliceProviderWrapperContainer$SliceProviderWrapper.attachInfo(SliceProviderWrapperContainer.java:74)
	at android.app.ActivityThread.installProvider(ActivityThread.java:7425)
	... 11 more

**Comment by ghost** [comment]
Excuse me, can you tell me how to fix this issue or is it caused by ROM source?

**Comment by AIV-97** [comment]
because rom source , in fw base , blinked  fixed in here https://github.com/NusantaraProject-ROM/android_frameworks_base/commits/12 see two latest commits
